### ISSUE TITLE
Alteração de Layout

### ISSUE THREAD

**Issue by CaioCesarS** [CaioCesarS/live#2]
![WhatsApp Image 2020-06-18 at 12.08.37.jpeg](https://zube.io/files/usecase/411a61523a026785a81ab8792074ef2f-whatsapp-image-2020-06-18-at-12-08-37.jpeg)

**Comment by VictorRasd** [comment]
Realizadas alterações do layout e criado menu do topo e feito tratamento para que o menu seja alterado conforme a página que o usuário está
